spring.application.name=Backend_FinalDrilling_m6_erickrivera
server.port=3000

# DATABASE CONNECTION
spring.datasource.url=jdbc:postgresql://localhost:5432/db_final_drilling_m6
spring.datasource.username=postgres
spring.datasource.password=12345678

# JPA Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# LOG CONFIG
logging.level.org.hibernate.SQL=TRACE
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate=ERROR

# JWT VARIABLES
security.key=d5c3a6576536e08f535961a93b3612d1ca0221b7f01aaf12a1dd144dff29ccf2
security.user=AUTHJWT0-BACKEND